-- Schema for QA Hub persistence, migrated from the SQLite schema in server/db.ts.
-- Table names and columns match server/db.ts exactly; SQLite types are mapped to
-- their closest Postgres equivalents (see mapping notes in the PR/commit message).

create table if not exists issues (
  id text primary key,
  key text not null,
  title text not null,
  area text not null,
  severity text not null,
  status text not null,
  "firstSeen" text not null,
  "lastSeen" text not null,
  persona text not null,
  url text not null,
  description text not null,
  "reproSteps" text not null,
  expected text not null,
  actual text not null,
  "screenshotThumbnail" text,
  "stackTrace" text,
  "jiraKey" text,
  "jiraUrl" text
);

create table if not exists runs (
  id text primary key,
  timestamp text not null,
  persona text not null,
  "targetRoute" text not null,
  findings text not null,
  status text not null,
  duration text not null,
  "suiteName" text not null,
  "recordedAt" bigint not null
);

create table if not exists pins (
  id text primary key,
  "xPercent" double precision not null,
  "yPercent" double precision not null,
  title text not null,
  description text not null,
  severity text not null,
  "pageUrl" text not null,
  "elementSelector" text not null,
  timestamp text not null,
  author text not null,
  status text not null
);

create table if not exists products (
  -- "by default" (not "always"): the app upserts explicit client-supplied
  -- ids, which "generated always as identity" rejects without
  -- OVERRIDING SYSTEM VALUE (not exposed by the Supabase JS client).
  id integer generated by default as identity primary key,
  name text not null,
  price double precision not null,
  "extractedPriceStr" text not null,
  "imgUrl" text not null,
  "isBrokenImage" boolean not null,
  "isDuplicateAsset" boolean not null,
  "duplicateNote" text,
  "isPriceGlitch" boolean not null,
  "missingDescription" boolean not null,
  location text not null,
  "deepLink" text not null,
  status text not null,
  "statusLabel" text not null
);
